#!/usr/bin/env bash

set -eo pipefail

echo "Testing with Clojure 1.11.1"
lein with-profiles +clojure-1.11.1 test "$@"

echo "Testing with Clojure 1.12.6"
lein with-profiles +clojure-1.12.6 test "$@"
