#!/usr/bin/env bash

set -eo pipefail

echo "Testing with Clojure 1.9.0"
lein with-profiles +clojure-1.9.0 test "$@"

echo "Testing with Clojure 1.10.3"
lein with-profiles +clojure-1.10.3 test "$@"

echo "Testing with Clojure 1.11.1"
lein with-profiles +clojure-1.11.1 test "$@"
