#!/usr/bin/env bash

set -eo pipefail

if [ -z "$GRAALVM_HOME" ]; then
    echo "Please set GRAALVM_HOME"
    exit 1
fi

"$GRAALVM_HOME/bin/gu" install native-image || true
export PATH=$GRAALVM_HOME/bin:$PATH

SCI_VERSION=$(cat resources/SCI_VERSION)

SCI_JAR=target/sci-$SCI_VERSION-standalone.jar
lein with-profiles +libsci,+native-image do clean, uberjar

SVM_JAR=$(find "$GRAALVM_HOME" | grep svm.jar)
$GRAALVM_HOME/bin/javac -cp "$SCI_JAR:$SVM_JAR" libsci/src/sci/impl/LibSci.java

$GRAALVM_HOME/bin/native-image \
  -jar $SCI_JAR \
  -cp libsci/src \
  -H:Name=libsci \
  --shared \
  -H:+ReportExceptionStackTraces \
  -J-Dclojure.spec.skip-macros=true \
  -J-Dclojure.compiler.direct-linking=true \
  "-H:IncludeResources=SCI_VERSION" \
  -H:ReflectionConfigurationFiles=reflection.json \
  --initialize-at-build-time  \
  -H:Log=registerResource: \
  --verbose \
  --no-fallback \
  --no-server \
  "-J-Xmx3g"

rm -rf libsci/target
mkdir -p libsci/target

mv graal_isolate_dynamic.h libsci.h graal_isolate.h libsci.dylib libsci_dynamic.h libsci/target
