name: CI

on: [push, pull_request]

jobs:

  test-jvm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch_depth: 0

      - name: Setup Babashka
        uses: turtlequeue/setup-babashka@v1.3.0
        with:
          babashka-version: 0.8.0

      - name: Prepare java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '8'

      - name: Run clj tests
        run: bb test:jvm

  test-node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch_depth: 0

      - name: Setup Babashka
        uses: turtlequeue/setup-babashka@v1.3.0
        with:
          babashka-version: 0.8.0

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@4.0
        with:
          cli: latest

      - name: Prepare java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '8'

      - name: Run node tests
        run: bb test:node

  test-native:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch_depth: 0

      - name: Setup Babashka
        uses: turtlequeue/setup-babashka@v1.3.0
        with:
          babashka-version: 0.8.0

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@4.0
        with:
          cli: latest

      - name: foo
        run: HOMEBREW_NO_AUTO_UPDATE=1 brew install planck

      - name: Run self-hosted tests
        run: bb test:self-hosted
